export default [
  {
    key: 1,
    name: 'price',
    title: 'Price ($)',
    startValue: 30,
    changeValue: .5,
  },
  {
    key: 2,
    name: 'marketing',
    title: 'Marketing ($000)',
    startValue: 100,
    changeValue: 5,
  },
  {
    key: 3,
    name: 'quality',
    title: 'Quality ($000)',
    startValue: 100,
    changeValue: 5,
  },
  {
    key: 4,
    name: 'technology',
    title: 'Technology ($000)',
    startValue: 100,
    changeValue: 5,
  },
  {
    key: 5,
    name: 'incentives',
    title: 'Incentives ($000)',
    startValue: 105,
    changeValue: 5,
  },
  {
    key: 6,
    name: 'dividends',
    title: 'Dividends ($000)',
    startValue: 0,
    changeValue: 5,
  },
  {
    key: 7,
    name: 'tBillInvestments',
    title: 'T-Bill Invest',
    startValue: 0,
    changeValue: 10,
  },
  {
    key: 8,
    name: 'loanPay',
    title: 'Loan Pay ($000)',
    startValue: 0,
    changeValue: 10,
  },
  {
    key: 9,
    name: 'production',
    title: 'Production',
    startValue: 80,
    changeValue: 1,
  },
];