name: bussim app
on: [push]
  # push:
  #   branches:
  #     - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "linting the project"
  tests:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "testing the project"
  build:
    needs: [linting, tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "building bussim"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download bussim-build
      - uses: actions/checkout@v2
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: ls -la
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUS_SIM_BAE06 }}'
          channelId: live
          projectId: bus-sim-bae06
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels