name: bussim app
on: [push]
  # push:
  #   branches:
  #     - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "linting the project"
  tests:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "testing the project"
  build:
    needs: [linting, tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "building bussim"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo"deploying project to firebase"


