name: bussim app
on: [push]
  # push:
  #   branches:
  #     - master
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "linting the project"
  tests:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing the project"
  build:
    needs: [linting, tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "building the project"
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo"deploying project to firebase"


